name: Deploy Helm Chart to GCP Artifact Registry

on:
  push:
    branches:
      - development

jobs:
  package-and-push-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          workload_identity_provider: 'projects/448693639111/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'hem-artifact-registry-write-sa@project-naresh-69399.iam.gserviceaccount.com'
          export_default_credentials: true
      
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Package Helm Chart
        id: package_chart
        run: |
          helm package . --destination ./build
          echo "CHART_PATH=$(ls ./build/*.tgz)" >> $GITHUB_ENV

      - name: Publish Helm Chart to Artifact Registry
        run: |
          CHART_PATH=${{ env.CHART_PATH }}
          HELM_CHART_NAME=$(basename $CHART_PATH .tgz)
          helm push $CHART_PATH oci://us-central1-docker.pkg.dev/project-naresh-69399/helm-ar-test/$HELM_CHART_NAME


